apiVersion: v1
kind: Service
metadata:
  name: bookmoa-backend-service
  labels:
    app: bookmoa-backend
spec:
  type: LoadBalancer
  selector:
    app: bookmoa-backend
  ports:
    - name: http
      port: 80
      targetPort: 3000
